#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

# forward declarations
class User < ::ProtocolBuffers::Message; end
class Group < ::ProtocolBuffers::Message; end

class User < ::ProtocolBuffers::Message
  set_fully_qualified_name "User"

  required :string, :name, 1
  required :string, :email, 2
  optional :int32, :logins, 3
end

class Group < ::ProtocolBuffers::Message
  # forward declarations

  # enums
  module GroupType
    include ::ProtocolBuffers::Enum

    set_fully_qualified_name "Group.GroupType"

    Study = 1
    Play = 2
    Rest = 3
  end

  set_fully_qualified_name "Group"

  repeated ::User, :users, 1
  repeated ::Group, :subgroups, 2
  optional ::Group::GroupType, :group_type, 3
end

