# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nested.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("nested.proto", :syntax => :proto3) do
    add_message "SearchResponse" do
      repeated :results, :message, 1, "SearchResponse.Result"
    end
    add_message "SearchResponse.Result" do
      optional :url, :string, 1
      optional :title, :string, 2
      repeated :snippets, :string, 3
    end
  end
end

SearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SearchResponse").msgclass
SearchResponse::Result = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SearchResponse.Result").msgclass
